#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MultiNotes.XAndroid.Resource", IsApplication=true)]

namespace MultiNotes.XAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int Blue = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int Darkblue = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int Darkgreen = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Darkorange = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int Darkpurple = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int Darkred = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int Green = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Orange = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int Purple = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int Red = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int ToolbarBackgroundColor = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ToolbarTextColor = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int DefaultMargin50 = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_account = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_create_2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_content_save_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int NotesIcon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int AcountExampleTextView = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int Main_SignInButton = 2131296259;
			
			// aapt resource value: 0x7f090015
			public const int MenuAccount = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int MenuEdit = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int MenuSave = 2131296276;
			
			// aapt resource value: 0x7f090006
			public const int SignIn_EmailAddressEditText = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int SignIn_EmailAddressTextView = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int SignIn_PasswordEditText = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int SignIn_PasswordTextView = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int SignIn_SignInButton = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int SignIn_SignUpButton = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int SignUp_EmailAddressEditText = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int SignUp_EmailAddressTextView = 2131296268;
			
			// aapt resource value: 0x7f09000f
			public const int SignUp_PasswordEditText = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int SignUp_PasswordTextView = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int SignUp_RepeatPasswordEditText = 2131296273;
			
			// aapt resource value: 0x7f090010
			public const int SignUp_RepeatPasswordTextView = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int SignUp_SignUpButton = 2131296274;
			
			// aapt resource value: 0x7f090000
			public const int ToolbarAccount = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int ToolbarMain = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int ToolbarSignIn = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int ToolbarSignUp = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SignIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SignUp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ToolbarMain = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int TopMenus = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000d
			public const int AcceptRules = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int EmailAddressTextView = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int MenuAccount = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int MenuDelete = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int MenuEdit = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int MenuMore = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int MenuPreferences = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int MenuSave = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int PasswordTextView = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int RepeatPasswordTextView = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int SignInButton = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int SignUpButton = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ToolbarAccountTitle = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int ToolbarSignInTitle = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ToolbarSignUpTitle = 2131099657;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MalczuuuTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MalczuuuThemeToolbar = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
