#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MultiNotes.XAndroid.Resource", IsApplication=true)]

namespace MultiNotes.XAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int SignInFormMargin = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_account = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NotesIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int EmailAddressEditText = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int EmailAddressTextView = 2131230723;
			
			// aapt resource value: 0x7f08000f
			public const int MenuAccount = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int MenuEdit = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MenuSave = 2131230734;
			
			// aapt resource value: 0x7f080008
			public const int MoveToSignUpButton = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int MyButton = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int PasswordEditText = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int PasswordTextView = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int RepeatPasswordEditText = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int RepeatPasswordTextView = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int SignInButton = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int SignUpButton = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int ToolbarMain = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int ToolbarSignIn = 2131230722;
			
			// aapt resource value: 0x7f080009
			public const int ToolbarSignUp = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SignIn = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SignUp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ToolbarMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ToolbarSignIn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ToolbarSignUp = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int TopMenus = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000d
			public const int AcceptRules = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int EmailAddressTextView = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int MenuAccount = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int MenuDelete = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int MenuEdit = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int MenuMore = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int MenuPreferences = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int MenuSave = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int PasswordTextView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int RepeatPasswordTextView = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int SignInButton = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int SignUpButton = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int ToolbarSignInTitle = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ToolbarSignUpTitle = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MalczuuuTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
